### - REGISTER A USER
POST http://localhost:3000/api/employee/register
Content-Type: application/json

  {
    "FirstName": "Maryann",
    "LastName": "Johnson",
    "Address": "123 Pine Street",
    "BirthDate": "1993-04-25T00:00:00.000Z",
    "ContactInfo": "1357924680",
    "Gender": "Female",
    "Position": "UX Designer",
    "imageUrl": "https://example.com/emily.jpg",
    "Email": "emily1234.johnson@example.com",
    "Password": "$2b$05$1Swl7ja6B.8YKp1O1.FRxeXA7IzIavry42uz3Ci.n1WIaVQ3zuacW",
    "HourlyRate": 55,
    "GrossPay": 275,
    "NHIFDeduction": 18,
    "NSSFDeduction": 22,
    "HELBDeduction": 14,
    "Role": "Employee"
  }

### - get all employeese
GET http://localhost:3000/api/employee


#### - UPDATE EMPLOYEE
PUT http://localhost:3000/api/employee/fce8e12d-d52b-47c3-809a-8af2ce52409e
Content-Type: application/json

{
    "PhotoURL": "TEST"
}

#### - login 
POST http://localhost:3000/api/employee/login
Content-Type: application/json

{
    "Email": "emily.johns1on@example.com",
    "Password": "$2b$05$5H4yfeR8n38raQUArw6KwelHFK6Psj8YtgXKgUe0g11TbSPKzT1d2"
}


### get user by id
GET http://localhost:3000/api/employee/626d3b67-049e-4c35-96b3-3cb45e2f18ba

### delete employee
DELETE  http://localhost:3000/api/employee/024508ae-7ac9-4b39-890d-aaa4a8d2d4d9
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbXBsb3llZUlEIjoiMjZiNTYxZmItNjU4Mi00MjZmLWI3YmQtMmJlZmU3ZGU0ODc1IiwiaWF0IjoxNzExNDM0MzY0LCJleHAiOjE3MTE2OTM1NjR9.uY36EWQ1-HxCFfDmGMErfPtCFpt11Ii4HBLz8LScgiA

##########################################################################################################
### - TIME

### Create time
POST http://localhost:3000/api/createTime
Content-Type: application/json

{
    "EmployeeID": "fce8e12d-d52b-47c3-809a-8af2ce52409e",
    "ClockInTime": "08:30",
    "ClockOutTime": "22:35",
    "Rate": 10
}

### - get ALL TIMES
GET http://localhost:3000/api/getTime


### - get ALL TIMES BY ID
GET http://localhost:3000/api/getTimeByEmployeeID/fce8e12d-d52b-47c3-809a-8af2ce52409e

### update the time
POST http://localhost:3000/api/updateTime
Content-Type: application/json

{
    "EmployeeID": "ef0dd005-d9d3-4686-9b4a-3ebc1a378083",
    "ClockInTime": "08:00",
    "ClockOutTime": "17:13",
    "Rate": 110
}

### get the best employee
GET http://localhost:3000/api/bestemployee

### NUMBER OF HOURS
GET http://localhost:3000/api/hoursworked


##### - payrolls -------------------------------------------------------------------------------------
### generate all payrolls
GET http://localhost:3000/api/payroll


### GET A PAROLL BY ITS ID
GET http://localhost:3000/api/payroll/9682cf74-8801-42fc-a801-338d71cc1584

### DELETE A PAYROLL
DELETE http://localhost:3000/api/payroll/



#### - advances ------------------------------------------------------------------------------------
POST http://localhost:3000/api/createAdvance
Content-Type: application/json

{
    "EmployeeID": "ef0dd005-d9d3-4686-9b4a-3ebc1a378083",
    "Amount": 300
}


##### SCHEDULES ------------------------------------------
## -- create schedule
POST http://localhost:3000/api/schedule
Content-Type: application/json

{
    "EmployeeID": "7cc982dd-5042-41ea-860b-a424a9e93b8a",
    "OnLeave": 1,
    "LeaveDays": 10
}

### get schedule by id
GET http://localhost:3000/api/schedule/e4f90aca-d944-4b8a-b4d7-aaafcd4b721d

### update schedule
PUT http://localhost:3000/api/schedule/e4f90aca-d944-4b8a-b4d7-aaafcd4b721d
Content-Type: application/json

{
    "ScheduleID": "e4f90aca-d944-4b8a-b4d7-aaafcd4b721d",
    "OnLeave": 1,
    "LeaveDays": 30
}

### upload image
GET http://localhost:3000/api/get-picture/Untitled.jpg


### - get all employeese
GET http://localhost:3000/api/employee

### create Email Service
POST http://localhost:3000/api/email
Content-Type: application/json

{
    "EmployeeID": "fce8e12d-d52b-47c3-809a-8af2ce52409e",
    "EmailSubject": "THIS IS YOUR FIRST TASK",
    "EmailContent": "BAZU BAZU",
    "Emailbody": "jeff last email"
}

### GET EMAILS
GET http://localhost:3000/api/email/fce8e12d-d52b-47c3-809a-8af2ce52409e

### GET ALL MAILS
GET http://localhost:3000/api/email

### NUMBER OF ACTIVITIES
GET http://localhost:3000/api/emails